/* ==========================================================================
   js/interactions.js — Interactions pipeline documentation barrel

   ⚠️ THIS FILE IS NOT LOADED. It exists as a single place to look when
   you want to understand the interactions pipeline structure without
   opening every partial.

   The actual pipeline is split into partials under js/interactions/ and
   is loaded via <script> tags in index.html, in this order:

     js/interactions/_nav.js       qs/qsa helpers, getActiveSectionId,
                                   folder tree clicks, section navigation,
                                   syncActiveSection, tab clicks, drawer
                                   link clicks
     js/interactions/_theme.js     THEME_STORAGE_KEY, setTheme, toggleTheme,
                                   syncThemeControls, handleThemeToggleClick
     js/interactions/_view.js      setView, handleViewToggleClick
     js/interactions/_search.js    SEARCH_DEBOUNCE_MS, EMPTY_STATE_CLASS,
                                   DRIVE_EMPTY_STATE_CLASS, debounce,
                                   getCurrentSearchQuery, toggleEmptyState,
                                   cardMatchesCategory, cardMatchesSearch,
                                   filterGrid, filterCards, syncSearchInputs,
                                   handleSearchInput
     js/interactions/_chips.js     activeCategory state, syncActiveCategoryUI,
                                   setActiveCategory, handleChipClick
     js/interactions/_drawer.js    focusFirstFocusable, trapFocus,
                                   handleDrawerKeydown, openDrawer,
                                   closeDrawer, handleDrawerOpenClick,
                                   handleDrawerBackdropClick
     js/interactions/_modal.js     findItemById, openModalForCard, closeModal,
                                   handleCardActivate, handleCardKeydown,
                                   handleModalCloseClick, handleModalKeydown
     js/interactions/_sidebar.js   toggleSidebarCollapse
     js/interactions/_bootstrap.js handleFabClick, handleDocumentClick, init,
                                   window.interactions assembly
     js/interactions/index.js      ← the actual entry point

   The single entry point is js/interactions/index.js, which calls
   window.interactions.init() after all partials have loaded.

   DO NOT edit this file to add interaction handlers. Edit the relevant
   partial. This file is documentation only.
   ========================================================================== */