/* ==========================================================================
   js/render.js — Render pipeline documentation barrel

   ⚠️ THIS FILE IS NOT LOADED. It exists as a single place to look when
   you want to understand the render pipeline structure without opening
   every partial.

   The actual pipeline is split into partials under js/render/ and is
   loaded via <script> tags in index.html, in this order:

     js/render/_shell.js       shared DOM helpers (el, clearChildren,
                               getSection, uniqueInOrder, applyGridMode),
                               icon helpers (buildIcon, replaceIconSlot,
                               hydrateIcons, renderThemeToggleIcons),
                               renderMeta, folder tree
                               (buildFolderTreeItem, renderFolderTree),
                               renderCounts
     js/render/_cards.js       buildThumbSlot, attachCardInteraction,
                               buildDashboardCard, buildDriveCard
     js/render/_chips.js       buildChip, renderFilterChips
     js/render/_sections.js    About + Contact block builders,
                               renderAboutSection, renderContactSection,
                               renderDashboard, renderDriveGrid,
                               renderSectionHeader, renderBreadcrumb
     js/render/_modal.js       renderModalContent (including the
                               collapsible <details> Core Features block)
     js/render/_drawer.js      renderDrawerList, renderMobileTabs
     js/render/_bootstrap.js   render config (window.__render.config),
                               renderSection, renderAll, window.render
                               assembly, data guard
     js/render/index.js        ← the actual entry point

   The single entry point is js/render/index.js, which calls
   window.render.renderAll() after all partials have loaded.

   DO NOT edit this file to add render functions. Edit the relevant
   partial. This file is documentation only.
   ========================================================================== */